// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ksj.Service.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GroceryLine
    {
        /// <summary>
        /// Initializes a new instance of the GroceryLine class.
        /// </summary>
        public GroceryLine()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GroceryLine class.
        /// </summary>
        public GroceryLine(int? amount = default(int?), Grocery grocery = default(Grocery), string unit = default(string))
        {
            Amount = amount;
            Grocery = grocery;
            Unit = unit;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public int? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Grocery")]
        public Grocery Grocery { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Unit")]
        public string Unit { get; set; }

    }
}
