// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ksj.Service.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Grocery
    {
        /// <summary>
        /// Initializes a new instance of the Grocery class.
        /// </summary>
        public Grocery()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Grocery class.
        /// </summary>
        public Grocery(string name = default(string), string pluralName = default(string), int? kcalPer100g = default(int?), int? averageGramsPerUnit = default(int?), string unitName = default(string), string id = default(string), IList<Category> category = default(IList<Category>))
        {
            Name = name;
            PluralName = pluralName;
            KcalPer100g = kcalPer100g;
            AverageGramsPerUnit = averageGramsPerUnit;
            UnitName = unitName;
            Id = id;
            Category = category;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PluralName")]
        public string PluralName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KcalPer100g")]
        public int? KcalPer100g { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AverageGramsPerUnit")]
        public int? AverageGramsPerUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitName")]
        public string UnitName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public IList<Category> Category { get; set; }

    }
}
