// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ksj.Service.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Instruction
    {
        /// <summary>
        /// Initializes a new instance of the Instruction class.
        /// </summary>
        public Instruction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Instruction class.
        /// </summary>
        public Instruction(string headline = default(string), string description = default(string))
        {
            Headline = headline;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Headline")]
        public string Headline { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
