// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ksj.Service.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Meal
    {
        /// <summary>
        /// Initializes a new instance of the Meal class.
        /// </summary>
        public Meal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Meal class.
        /// </summary>
        public Meal(IList<GroceryLine> groceries = default(IList<GroceryLine>), string name = default(string), IList<Instruction> instructions = default(IList<Instruction>), int? numberOfPersons = default(int?), IList<Category> category = default(IList<Category>), System.Guid? id = default(System.Guid?))
        {
            Groceries = groceries;
            Name = name;
            Instructions = instructions;
            NumberOfPersons = numberOfPersons;
            Category = category;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Groceries")]
        public IList<GroceryLine> Groceries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Instructions")]
        public IList<Instruction> Instructions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfPersons")]
        public int? NumberOfPersons { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public IList<Category> Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid? Id { get; set; }

    }
}
